apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webapp
spec:
  replications: 1 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels: 
        app: webapp
    spec:
      containers:
      - name: webapp
        image: your_image_name:v1.0
        ports: 
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000